# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CheckCoordinates
                                 A QGIS plugin
 This plugin checks coordinates and displays list of coordinate system for which x and y are inside bounds
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-06-24
        copyright            : (C) 2021 by Paweł Jankowski
        email                : paweljankowski246@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CheckCoordinates class from file CheckCoordinates.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .check_coordinates import CheckCoordinates
    return CheckCoordinates(iface)
